"""add phone number

Revision ID: 6d910bdeb4dd
Revises: e92a70b5a712
Create Date: 2023-06-06 11:04:38.062869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d910bdeb4dd'
down_revision = 'e92a70b5a712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('users')
    # op.drop_table('bike')
    op.add_column('login', sa.Column('phone_number', sa.String(), nullable=True))
    # op.add_column('posts', sa.Column('content', sa.String(), nullable=False))
    # op.drop_constraint('posts_users_fk', 'posts', type_='foreignkey')
    # op.create_foreign_key(None, 'posts', 'login', ['owner_id'], ['id'], ondelete='CASCADE')
    # op.drop_column('posts', 'contenet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('posts', sa.Column('contenet', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'posts', type_='foreignkey')
    # op.create_foreign_key('posts_users_fk', 'posts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # op.drop_column('posts', 'content')
    op.drop_column('login', 'phone_number')
    # op.create_table('bike',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('registration_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('brand', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('loc', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('ownership_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('kms_driven', sa.BIGINT(), autoincrement=False, nullable=False),
    # sa.Column('power', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('manufactured_date', sa.DATE(), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='bike_pkey')
    # )
    # op.create_table('users',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('pasword', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='users_pkey'),
    # sa.UniqueConstraint('email', name='users_email_key')
    # )
    # ### end Alembic commands ###
