"""add votes

Revision ID: e92a70b5a712
Revises: 221fc896afd4
Create Date: 2023-06-06 10:56:40.275137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e92a70b5a712'
down_revision = '221fc896afd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['login.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # op.drop_table('bike')
    # op.drop_table('users')
    # op.add_column('posts', sa.Column('content', sa.String(), nullable=False))
    # op.drop_constraint('posts_users_fk', 'posts', type_='foreignkey')
    # op.create_foreign_key(None, 'posts', 'login', ['owner_id'], ['id'], ondelete='CASCADE')
    # op.drop_column('posts', 'contenet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('contenet', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_users_fk', 'posts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'content')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pasword', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('bike',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('registration_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('loc', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ownership_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('kms_driven', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('power', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manufactured_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bike_pkey')
    )
    op.drop_table('votes')
    # ### end Alembic commands ###
